config/routes.rb
Katello::Engine.routes.draw do
  resources :systems
  resources :activation_keys

  root :to => 'systems#index'
end

app/models/katello/activation_key.rb
module Katello
  class ActivationKey < ActiveRecord::Base
    attr_accessible :name
  end
end

app/models/katello/system.rb
module Katello
  class System < ActiveRecord::Base
    attr_accessible :name
  end
end

app/controllers/katello/activation_keys_controller.rb
module Katello
  class ActivationKeysController < ApplicationController
    # GET /activation_keys
    # GET /activation_keys.json
    def index
      @activation_keys = ActivationKey.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @activation_keys }
      end
    end

    # GET /activation_keys/1
    # GET /activation_keys/1.json
    def show
      @activation_key = ActivationKey.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @activation_key }
      end
    end

    # GET /activation_keys/new
    # GET /activation_keys/new.json
    def new
      @activation_key = ActivationKey.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @activation_key }
      end
    end

    # GET /activation_keys/1/edit
    def edit
      @activation_key = ActivationKey.find(params[:id])
    end

    # POST /activation_keys
    # POST /activation_keys.json
    def create
      @activation_key = ActivationKey.new(params[:activation_key])

      respond_to do |format|
        if @activation_key.save
          format.html { redirect_to @activation_key, notice: 'Activation key was successfully created.' }
          format.json { render json: @activation_key, status: :created, location: @activation_key }
        else
          format.html { render action: "new" }
          format.json { render json: @activation_key.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /activation_keys/1
    # PUT /activation_keys/1.json
    def update
      @activation_key = ActivationKey.find(params[:id])

      respond_to do |format|
        if @activation_key.update_attributes(params[:activation_key])
          format.html { redirect_to @activation_key, notice: 'Activation key was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @activation_key.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /activation_keys/1
    # DELETE /activation_keys/1.json
    def destroy
      @activation_key = ActivationKey.find(params[:id])
      @activation_key.destroy

      respond_to do |format|
        format.html { redirect_to activation_keys_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/katello/application_controller.rb
class Katello::ApplicationController < ::ApplicationController
  layout 'application'
  helper :all
end

app/controllers/katello/systems_controller.rb
module Katello
  class SystemsController < ApplicationController
    # GET /systems
    # GET /systems.json
    def index
      @systems = System.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @systems }
      end
    end

    # GET /systems/1
    # GET /systems/1.json
    def show
      @system = System.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @system }
      end
    end

    # GET /systems/new
    # GET /systems/new.json
    def new
      @system = System.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @system }
      end
    end

    # GET /systems/1/edit
    def edit
      @system = System.find(params[:id])
    end

    # POST /systems
    # POST /systems.json
    def create
      @system = System.new(params[:system])

      respond_to do |format|
        if @system.save
          format.html { redirect_to @system, notice: 'System was successfully created.' }
          format.json { render json: @system, status: :created, location: @system }
        else
          format.html { render action: "new" }
          format.json { render json: @system.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /systems/1
    # PUT /systems/1.json
    def update
      @system = System.find(params[:id])

      respond_to do |format|
        if @system.update_attributes(params[:system])
          format.html { redirect_to @system, notice: 'System was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @system.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /systems/1
    # DELETE /systems/1.json
    def destroy
      @system = System.find(params[:id])
      @system.destroy

      respond_to do |format|
        format.html { redirect_to systems_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/katello/activation_keys_helper.rb
module Katello
  module ActivationKeysHelper
  end
end

app/helpers/katello/application_helper.rb
module Katello
  module ApplicationHelper
  end
end

app/helpers/katello/systems_helper.rb
module Katello
  module SystemsHelper
  end
end

app/views/katello/activation_keys/_form.html.erb
<%= form_for(@activation_key) do |f| %>
  <% if @activation_key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activation_key.errors.count, "error") %> prohibited this activation_key from being saved:</h2>

      <ul>
      <% @activation_key.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/katello/activation_keys/edit.html.erb
<h1>Editing activation_key</h1>

<%= render 'form' %>

<%= link_to 'Show', @activation_key %> |
<%= link_to 'Back', activation_keys_path %>

app/views/katello/activation_keys/index.html.erb
<h1>Listing activation_keys</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activation_keys.each do |activation_key| %>
  <tr>
    <td><%= activation_key.name %></td>
    <td><%= link_to 'Show', activation_key %></td>
    <td><%= link_to 'Edit', edit_activation_key_path(activation_key) %></td>
    <td><%= link_to 'Destroy', activation_key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activation key', new_activation_key_path %>

app/views/katello/activation_keys/new.html.erb
<h1>New activation_key</h1>

<%= render 'form' %>

<%= link_to 'Back', activation_keys_path %>

app/views/katello/activation_keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @activation_key.name %>
</p>


<%= link_to 'Edit', edit_activation_key_path(@activation_key) %> |
<%= link_to 'Back', activation_keys_path %>

app/views/katello/systems/_form.html.erb
<%= form_for(@system) do |f| %>
  <% if @system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system.errors.count, "error") %> prohibited this system from being saved:</h2>

      <ul>
      <% @system.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/katello/systems/edit.html.erb
<h1>Editing system</h1>

<%= render 'form' %>

<%= link_to 'Show', @system %> |
<%= link_to 'Back', systems_path %>

app/views/katello/systems/index.html.erb
<h1>Listing systems</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @systems.each do |system| %>
  <tr>
    <td><%= system.name %></td>
    <td><%= link_to 'Show', system_path(system.id) %></td>
    <td><%= link_to 'Edit', edit_system_path(system) %></td>
    <td><%= link_to 'Destroy', system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New System', new_system_path %>

app/views/katello/systems/new.html.erb
<h1>New system</h1>

<%= render 'form' %>

<%= link_to 'Back', systems_path %>

app/views/katello/systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @system.name %>
</p>


<%= link_to 'Edit', edit_system_path(@system) %> |
<%= link_to 'Back', systems_path %>

app/views/layouts/katello/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Katello</title>
  <%= stylesheet_link_tag    "katello/application", :media => "all" %>
  <%= javascript_include_tag "katello/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>